import {
  User,
  Shop,
  Product,
  Category,
  City,
  Market,
  Order,
  Review,
  Commission,
  MerchantSubscription,
  Report,
  Notification,
  PlatformSettings,
} from '../types';

export const initialCities: City[] = [
  { id: 'city-1', name: 'Mbandaka', province: 'Équateur', territory: 'Mbandaka' },
  { id: 'city-2', name: 'Gemena', province: 'Sud-Ubangi', territory: 'Gemena' },
  { id: 'city-3', name: 'Karawa', province: 'Sud-Ubangi', territory: 'Bwamanda' },
  { id: 'city-4', name: 'Gbadolite', province: 'Nord-Ubangi', territory: 'Gbadolite' },
  { id: 'city-5', name: 'Lisala', province: 'Mongala', territory: 'Lisala' },
  { id: 'city-6', name: 'Bumba', province: 'Mongala', territory: 'Bumba' },
  { id: 'city-7', name: 'Boende', province: 'Tshuapa', territory: 'Boende' },
  { id: 'city-8', name: 'Kinshasa', province: 'Kinshasa', territory: 'Kinshasa' },
  { id: 'city-9', name: 'Businga', province: 'Nord-Ubangi', territory: 'Businga' },
  { id: 'city-10', name: 'Zongo', province: 'Sud-Ubangi', territory: 'Zongo' },
];

export const initialMarkets: Market[] = [
  { id: 'mkt-1', name: 'Grand Marché Central de Mbandaka', city: 'Mbandaka', address: 'Avenue du Commerce, Mbandaka', shopCount: 38 },
  { id: 'mkt-2', name: 'Marché Bakusu', city: 'Mbandaka', address: 'Commune de Wangata, Mbandaka', shopCount: 22 },
  { id: 'mkt-3', name: 'Grand Marché de Gemena', city: 'Gemena', address: 'Centre commercial, Gemena', shopCount: 29 },
  { id: 'mkt-4', name: 'Marché Central de Karawa', city: 'Karawa', address: 'Poste commercial Karawa Mission', shopCount: 19 },
  { id: 'mkt-5', name: 'Marché Central de Gbadolite', city: 'Gbadolite', address: 'Boulevard Lumumba, Gbadolite', shopCount: 16 },
  { id: 'mkt-6', name: 'Marché de Lisala Port', city: 'Lisala', address: 'Zone portuaire fleuve Congo, Lisala', shopCount: 14 },
  { id: 'mkt-7', name: 'Marché de Bumba', city: 'Bumba', address: 'Quartier Lokole, Bumba', shopCount: 17 },
];

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Alimentation & Vivres', slug: 'alimentation', iconName: 'Apple', description: 'Poissons fumés, riz, bananes plantains, manioc, épices locales', productCount: 6 },
  { id: 'cat-2', name: 'Chaussures & Sandales', slug: 'chaussures', iconName: 'Footprints', description: 'Mocassins, sandales en cuir, baskets homme & femme', productCount: 5 },
  { id: 'cat-3', name: 'Téléphones & Accessoires', slug: 'telephones', iconName: 'Smartphone', description: 'Smartphones Android, chargeurs, powerbanks, écouteurs', productCount: 5 },
  { id: 'cat-4', name: 'Mode & Habillement', slug: 'mode', iconName: 'Shirt', description: 'Super Wax, chemises homme, robes femme, tenues élégantes', productCount: 5 },
  { id: 'cat-5', name: 'Produits Agricoles & Épicerie', slug: 'agricole', iconName: 'Wheat', description: 'Huile de palme pure rouge, café, arachides, semoules', productCount: 4 },
  { id: 'cat-6', name: 'Beauté & Soins', slug: 'beaute', iconName: 'Sparkles', description: 'Savons artisanaux au palmiste & coco, lotions, crèmes', productCount: 3 },
  { id: 'cat-7', name: 'Électronique & Solaire', slug: 'electronique', iconName: 'Zap', description: 'Kits solaires domestiques, radios rechargeables, ampoules LED', productCount: 3 },
  { id: 'cat-8', name: 'Maison & Décoration', slug: 'maison', iconName: 'Home', description: 'Ustensiles de cuisine, nattes, moustiquaires, literie', productCount: 3 },
  { id: 'cat-9', name: 'Produits Digitaux & E-books', slug: 'digitaux', iconName: 'FileText', description: 'E-books, formations en ligne, modèles de contrats, musique & créations numériques', productCount: 3 },
];

export const demoUsers: User[] = [
  {
    id: 'user-client-1',
    name: 'Josephine Mbemba (DEMO)',
    phone: '+243810123456',
    whatsapp: '+243810123456',
    email: 'client@marchelumumba.cd',
    role: 'CLIENT',
    city: 'Kinshasa',
    zone: 'Gombe',
    address: 'Avenue de la Paix n° 12, Kinshasa',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'user-merchant-1',
    name: 'Papa Jean-Luc Mboyo (DEMO)',
    phone: '+243820234567',
    whatsapp: '+243820234567',
    email: 'mboyo@marchelumumba.cd',
    role: 'COMMERÇANT',
    city: 'Mbandaka',
    address: 'Grand Marché Central de Mbandaka, Stand 12',
    shopId: 'shop-1',
    hasActiveSubscription: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T08:30:00Z',
  },
  {
    id: 'user-merchant-2',
    name: 'Maman Chantal Boketshu (DEMO)',
    phone: '+243899345678',
    whatsapp: '+243899345678',
    email: 'chantal@marchelumumba.cd',
    role: 'COMMERÇANT',
    city: 'Karawa',
    address: 'Marché central de Karawa, Stand 15',
    shopId: 'shop-2',
    hasActiveSubscription: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-11T10:00:00Z',
  },
  {
    id: 'user-merchant-3',
    name: 'Antoine Lokonda (DEMO)',
    phone: '+243990456789',
    whatsapp: '+243990456789',
    email: 'lokonda@marchelumumba.cd',
    role: 'COMMERÇANT',
    city: 'Karawa',
    address: 'Avenue Commerciale n° 4, Karawa',
    shopId: 'shop-3',
    hasActiveSubscription: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T11:00:00Z',
  },
  {
    id: 'user-admin-1',
    name: 'Administration Centrale (DEMO)',
    phone: '+243833358006',
    whatsapp: '+243833358006',
    email: 'sitdoworldinformatique@gmail.com',
    role: 'ADMINISTRATEUR',
    city: 'Kinshasa',
    address: 'Siège Central MARCHE LUMUMBA RDC',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const demoShops: Shop[] = [
  {
    id: 'shop-1',
    slug: 'maison-mboyo-vivres',
    ownerId: 'user-merchant-1',
    ownerName: 'Papa Jean-Luc Mboyo',
    ownerPhone: '+243820234567',
    ownerWhatsapp: '+243820234567',
    ownerEmail: 'mboyo@marchelumumba.cd',
    name: 'Maison Mboyo & Fils - Vivres Frais',
    description: 'Poissons capitaines fumés du fleuve, riz blanc de qualité supérieure et farine de manioc fufu.',
    category: 'Alimentation & Vivres',
    city: 'Mbandaka',
    address: 'Grand Marché Central de Mbandaka, Stand 12',
    marketName: 'Grand Marché Central de Mbandaka',
    standNumber: 'Stand 12',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&auto=format&fit=crop&q=80',
    isVerified: true,
    isApproved: true,
    rating: 4.9,
    reviewCount: 38,
    createdAt: '2026-01-10T08:30:00Z',
    totalSalesFc: 2450000,
  },
  {
    id: 'shop-2',
    slug: 'elegance-karawa-chantal',
    ownerId: 'user-merchant-2',
    ownerName: 'Maman Chantal Boketshu',
    ownerPhone: '+243899345678',
    ownerWhatsapp: '+243899345678',
    ownerEmail: 'chantal@marchelumumba.cd',
    name: 'Élégance Karawa - Wax & Confection',
    description: 'Pagnes Super Wax véritables, robes femme, chemises africaines et chaussures élégantes à Karawa.',
    category: 'Mode & Habillement',
    city: 'Karawa',
    address: 'Marché central de Karawa, stand 15',
    marketName: 'Marché central de Karawa',
    standNumber: 'Stand 15',
    logoUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    isVerified: true,
    isApproved: true,
    rating: 4.8,
    reviewCount: 29,
    createdAt: '2026-01-11T10:00:00Z',
    totalSalesFc: 1820000,
  },
  {
    id: 'shop-3',
    slug: 'lokonda-chaussures-terroir-karawa',
    ownerId: 'user-merchant-3',
    ownerName: 'Antoine Lokonda',
    ownerPhone: '+243990456789',
    ownerWhatsapp: '+243990456789',
    ownerEmail: 'lokonda@marchelumumba.cd',
    name: 'Lokonda Chaussures & Terroir - Karawa',
    description: 'Vente de chaussures homme, mocassins en cuir, sandales robustes et huile de palme rouge pure.',
    category: 'Chaussures & Sandales',
    city: 'Karawa',
    address: 'Avenue Commerciale n° 4, Karawa',
    marketName: 'Centre Commercial Karawa',
    standNumber: 'Boutique 4',
    logoUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&auto=format&fit=crop&q=80',
    isVerified: true,
    isApproved: true,
    rating: 4.9,
    reviewCount: 34,
    createdAt: '2026-01-12T11:00:00Z',
    totalSalesFc: 2150000,
  },
  {
    id: 'shop-4',
    slug: 'yoka-tech-mobile-solaire',
    ownerId: 'user-merchant-1',
    ownerName: 'Dieudonné Yoka',
    ownerPhone: '+243841678901',
    ownerWhatsapp: '+243841678901',
    ownerEmail: 'yoka@marchelumumba.cd',
    name: 'Yoka High-Tech Mobile & Solaire',
    description: 'Smartphones Android, powerbanks grande autonomie, chargeurs rapides et kits solaires pour la maison.',
    category: 'Téléphones & Accessoires',
    city: 'Mbandaka',
    address: 'Avenue du Port Commercial n° 21, Mbandaka',
    marketName: 'Grand Marché Central',
    standNumber: 'Stand Électro 21',
    logoUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80',
    isVerified: true,
    isApproved: true,
    rating: 4.9,
    reviewCount: 45,
    createdAt: '2026-01-14T09:30:00Z',
    totalSalesFc: 3950000,
  },
  {
    id: 'shop-5',
    slug: 'businga-mode-accessoires',
    ownerId: 'user-merchant-2',
    ownerName: 'Hélène Molengi',
    ownerPhone: '+243818567890',
    ownerWhatsapp: '+243818567890',
    ownerEmail: 'molengi@marchelumumba.cd',
    name: 'Molengi Mode & Sacs - Businga',
    description: 'Sacs à main, vêtements femme et articles de beauté naturels à Businga et environs.',
    category: 'Mode & Habillement',
    city: 'Businga',
    address: 'Marché central de Businga, Hangar Textile',
    marketName: 'Marché central de Businga',
    standNumber: 'Stand 08',
    logoUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
    isVerified: true,
    isApproved: true,
    rating: 4.7,
    reviewCount: 19,
    createdAt: '2026-01-15T14:00:00Z',
    totalSalesFc: 980000,
  },
  {
    id: 'shop-6',
    slug: 'kinshasa-express-market',
    ownerId: 'user-merchant-3',
    ownerName: 'Fabrice Boliko',
    ownerPhone: '+243970890123',
    ownerWhatsapp: '+243970890123',
    ownerEmail: 'boliko@marchelumumba.cd',
    name: 'Boliko Confort & Électroménager - Kinshasa',
    description: 'Meubles, ventilateurs rechargeables et appareils électroménagers expédiés dans toute la RDC.',
    category: 'Maison & Décoration',
    city: 'Kinshasa',
    address: 'Marché Central de Kinshasa, Allée des Meubles',
    marketName: 'Marché Central de Kinshasa',
    standNumber: 'Galerie 3, n° 10',
    logoUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&auto=format&fit=crop&q=80',
    isVerified: true,
    isApproved: true,
    rating: 4.8,
    reviewCount: 22,
    createdAt: '2026-01-18T10:15:00Z',
    totalSalesFc: 3100000,
  },
];

export const demoProducts: Product[] = [
  // Chaussures Karawa
  {
    id: 'prod-1',
    shopId: 'shop-3',
    shopName: 'Lokonda Chaussures & Terroir - Karawa',
    name: 'Chaussures de Ville Mocassins Cuir Homme Noires - Karawa',
    description: 'Mocassins homme en cuir véritable cousu main, semelle tout-terrain antidérapante. Très confortables.',
    price: 28000,
    oldPrice: 35000,
    discountPercent: 20,
    stock: 18,
    category: 'Chaussures & Sandales',
    images: [
      'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Karawa',
    address: 'Avenue Commerciale n° 4, Karawa',
    rating: 4.9,
    reviewCount: 16,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-2',
    shopId: 'shop-3',
    shopName: 'Lokonda Chaussures & Terroir - Karawa',
    name: 'Sandales Homme en Cuir Cousu Main Karawa',
    description: 'Sandales en cuir de bœuf épais avec lanières réglables. Conçues pour marcher durablement.',
    price: 22000,
    oldPrice: 26000,
    discountPercent: 15,
    stock: 24,
    category: 'Chaussures & Sandales',
    images: [
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Karawa',
    address: 'Avenue Commerciale n° 4, Karawa',
    rating: 4.8,
    reviewCount: 12,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-21T11:00:00Z',
  },
  {
    id: 'prod-3',
    shopId: 'shop-2',
    shopName: 'Élégance Karawa - Wax & Confection',
    name: 'Chaussures Sandales Femme Perles Karawa',
    description: 'Belles sandales féminines avec perles décoratives et semelle confortable.',
    price: 20000,
    stock: 15,
    category: 'Chaussures & Sandales',
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Karawa',
    address: 'Marché central de Karawa, stand 15',
    rating: 4.7,
    reviewCount: 9,
    createdAt: '2026-01-22T14:00:00Z',
  },
  {
    id: 'prod-4',
    shopId: 'shop-1',
    shopName: 'Maison Mboyo & Fils - Vivres Frais',
    name: 'Chaussures Baskets Basses Toile Mbandaka',
    description: 'Baskets confortables en toile respirante avec semelle en caoutchouc vulcanisé.',
    price: 26000,
    oldPrice: 30000,
    discountPercent: 13,
    stock: 12,
    category: 'Chaussures & Sandales',
    images: [
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Mbandaka',
    address: 'Grand Marché Central de Mbandaka, Stand 12',
    rating: 4.6,
    reviewCount: 11,
    createdAt: '2026-01-23T15:00:00Z',
  },

  // Téléphones
  {
    id: 'prod-5',
    shopId: 'shop-4',
    shopName: 'Yoka High-Tech Mobile & Solaire',
    name: 'Smartphone Android 64GB Double SIM 5000mAh',
    description: 'Smartphone robuste idéal pour WhatsApp, Mobile Money et les pistes. Grande autonomie 2 jours.',
    price: 175000,
    oldPrice: 199000,
    discountPercent: 12,
    stock: 14,
    category: 'Téléphones & Accessoires',
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Mbandaka',
    address: 'Avenue du Port Commercial n° 21',
    rating: 4.9,
    reviewCount: 28,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-24T10:00:00Z',
  },
  {
    id: 'prod-6',
    shopId: 'shop-4',
    shopName: 'Yoka High-Tech Mobile & Solaire',
    name: 'Powerbank Solaire 30000mAh Torche LED & 3 Sorties USB',
    description: 'Batterie externe solaire avec lampe torche puissante. Rechargez votre téléphone partout sans électricité.',
    price: 45000,
    oldPrice: 55000,
    discountPercent: 18,
    stock: 25,
    category: 'Téléphones & Accessoires',
    images: [
      'https://images.unsplash.com/photo-1609592426508-cc820ad27e82?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Mbandaka',
    address: 'Avenue du Port Commercial n° 21',
    rating: 4.9,
    reviewCount: 22,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-25T11:00:00Z',
  },
  {
    id: 'prod-7',
    shopId: 'shop-4',
    shopName: 'Yoka High-Tech Mobile & Solaire',
    name: 'Chargeur Rapide Universel Type-C & Câble Renforcé',
    description: 'Chargeur mural haute puissance avec câble résistant aux torsions.',
    price: 12000,
    stock: 40,
    category: 'Téléphones & Accessoires',
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Mbandaka',
    address: 'Avenue du Port Commercial n° 21',
    rating: 4.7,
    reviewCount: 15,
    createdAt: '2026-01-26T09:00:00Z',
  },

  // Alimentation (Riz, Poisson)
  {
    id: 'prod-8',
    shopId: 'shop-1',
    shopName: 'Maison Mboyo & Fils - Vivres Frais',
    name: 'Sac de Riz Blanc Parfumé Extra Qualité (25 kg)',
    description: 'Riz blanc grain long parfumé, trié sans cailloux. Cuisson parfaite pour toute la famille.',
    price: 52000,
    oldPrice: 58000,
    discountPercent: 10,
    stock: 30,
    category: 'Alimentation & Vivres',
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Mbandaka',
    address: 'Grand Marché Central de Mbandaka, Stand 12',
    rating: 4.9,
    reviewCount: 31,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-27T08:00:00Z',
  },
  {
    id: 'prod-9',
    shopId: 'shop-1',
    shopName: 'Maison Mboyo & Fils - Vivres Frais',
    name: 'Poisson Capitaine Fumé du Fleuve Congo (Lot de 3)',
    description: 'Véritable capitaine fumé selon la méthode traditionnelle du fleuve. Chair parfumée et tendre.',
    price: 35000,
    oldPrice: 42000,
    discountPercent: 16,
    stock: 20,
    category: 'Alimentation & Vivres',
    images: [
      'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Mbandaka',
    address: 'Grand Marché Central de Mbandaka, Stand 12',
    rating: 5.0,
    reviewCount: 26,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-28T09:00:00Z',
  },
  {
    id: 'prod-10',
    shopId: 'shop-3',
    shopName: 'Lokonda Chaussures & Terroir - Karawa',
    name: 'Huile de Palme Pure Rouge de Karawa (Bidon 5 Litres)',
    description: 'Huile de palme rouge première pression artisanale de Karawa. Très riche et parfumée.',
    price: 18000,
    oldPrice: 22000,
    discountPercent: 18,
    stock: 45,
    category: 'Produits Agricoles & Épicerie',
    images: [
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Karawa',
    address: 'Avenue Commerciale n° 4, Karawa',
    rating: 4.9,
    reviewCount: 24,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-29T10:00:00Z',
  },

  // Mode (Chemise homme, Robe femme, Pagne Super Wax, Sac)
  {
    id: 'prod-11',
    shopId: 'shop-2',
    shopName: 'Élégance Karawa - Wax & Confection',
    name: 'Chemise Homme Pagne Wax Style Africain - Karawa',
    description: 'Chemise élégante col officier en tissu Super Wax de haute qualité. Finitions sur mesure soignées.',
    price: 35000,
    oldPrice: 42000,
    discountPercent: 16,
    stock: 15,
    category: 'Mode & Habillement',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Karawa',
    address: 'Marché central de Karawa, stand 15',
    rating: 4.8,
    reviewCount: 14,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-30T11:00:00Z',
  },
  {
    id: 'prod-12',
    shopId: 'shop-2',
    shopName: 'Élégance Karawa - Wax & Confection',
    name: 'Robe Femme Longue Évasée en Pagne Wax',
    description: 'Robe féminine moderne, coupe fluide et confortable pour toutes les occasions.',
    price: 48000,
    oldPrice: 55000,
    discountPercent: 12,
    stock: 10,
    category: 'Mode & Habillement',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Karawa',
    address: 'Marché central de Karawa, stand 15',
    rating: 4.9,
    reviewCount: 18,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-01-31T12:00:00Z',
  },
  {
    id: 'prod-13',
    shopId: 'shop-5',
    shopName: 'Molengi Mode & Sacs - Businga',
    name: 'Sac à Main Femme Cuir & Finitions Dorées - Businga',
    description: 'Sac à main spacieux avec bandoulière et multiples compartiments zippés.',
    price: 32000,
    oldPrice: 38000,
    discountPercent: 15,
    stock: 12,
    category: 'Mode & Habillement',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Businga',
    address: 'Marché central de Businga, Hangar Textile',
    rating: 4.7,
    reviewCount: 9,
    createdAt: '2026-02-01T13:00:00Z',
  },

  // Beauté
  {
    id: 'prod-14',
    shopId: 'shop-5',
    shopName: 'Molengi Mode & Sacs - Businga',
    name: 'Savon Artisanal Purifiant au Palmiste Noir & Karité (Pack 4)',
    description: 'Produit de beauté 100% naturel pour purifier et adoucir la peau au quotidien.',
    price: 10000,
    stock: 35,
    category: 'Beauté & Soins',
    images: [
      'https://images.unsplash.com/photo-1608248597359-598d1a108f92?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Businga',
    address: 'Marché central de Businga',
    rating: 4.9,
    reviewCount: 20,
    createdAt: '2026-02-02T14:00:00Z',
  },

  // Maison / Meubles
  {
    id: 'prod-15',
    shopId: 'shop-6',
    shopName: 'Boliko Confort & Électroménager - Kinshasa',
    name: 'Meuble Table Basse Moderne en Bois Massif',
    description: 'Table basse robuste en bois tropical noble avec tiroir de rangement intégré.',
    price: 95000,
    oldPrice: 115000,
    discountPercent: 17,
    stock: 6,
    category: 'Maison & Décoration',
    images: [
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=600&auto=format&fit=crop&q=80',
    ],
    status: 'active',
    city: 'Kinshasa',
    address: 'Marché Central de Kinshasa, Allée des Meubles',
    rating: 4.8,
    reviewCount: 8,
    isPromoted: true,
    promoStartDate: '2026-01-01',
    promoEndDate: '2026-12-31',
    createdAt: '2026-02-03T09:00:00Z',
  },
];

export const demoOrders: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'MLM-2026-001',
    clientId: 'user-client-1',
    clientName: 'Josephine Mbemba (DEMO)',
    clientPhone: '+243810123456',
    clientWhatsapp: '+243810123456',
    clientEmail: 'client@marchelumumba.cd',
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        productName: 'Chaussures de Ville Mocassins Cuir Homme Noires - Karawa',
        productImage: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&auto=format&fit=crop&q=80',
        shopId: 'shop-3',
        shopName: 'Lokonda Chaussures & Terroir - Karawa',
        unitPrice: 28000,
        quantity: 1,
        totalPrice: 28000,
      },
    ],
    subtotal: 28000,
    deliveryFee: 0,
    totalAmount: 28000,
    status: 'delivered',
    deliveryType: 'home_delivery',
    deliveryAddress: {
      city: 'Karawa',
      quartier: 'Quartier Mission',
      streetDetails: 'Près de l’Hôpital de Karawa n° 12',
      recipientName: 'Josephine Mbemba',
      recipientPhone: '+243810123456',
      recipientWhatsapp: '+243810123456',
      deliveryInstructions: 'Remettre en main propre',
    },
    paymentMethod: 'mpesa',
    paymentStatus: 'paid',
    paymentTransactionRef: 'MPESA-TEST-TX78101',
    isTestPayment: true,
    commissionTotal: 1400,
    createdAt: '2026-02-10T14:30:00Z',
    updatedAt: '2026-02-10T16:15:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'MLM-2026-002',
    clientId: 'user-client-1',
    clientName: 'Josephine Mbemba (DEMO)',
    clientPhone: '+243810123456',
    clientWhatsapp: '+243810123456',
    items: [
      {
        id: 'item-2',
        productId: 'prod-10',
        productName: 'Huile de Palme Pure Rouge de Karawa (Bidon 5 Litres)',
        productImage: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
        shopId: 'shop-3',
        shopName: 'Lokonda Chaussures & Terroir - Karawa',
        unitPrice: 18000,
        quantity: 2,
        totalPrice: 36000,
      },
    ],
    subtotal: 36000,
    deliveryFee: 0,
    totalAmount: 36000,
    status: 'shipped',
    deliveryType: 'market_pickup',
    deliveryAddress: {
      city: 'Karawa',
      streetDetails: 'Retrait au stand d’Antoine Lokonda',
      recipientName: 'Josephine Mbemba',
      recipientPhone: '+243810123456',
    },
    paymentMethod: 'airtel',
    paymentStatus: 'paid',
    paymentTransactionRef: 'AIRTEL-TEST-004312',
    isTestPayment: true,
    commissionTotal: 1800,
    createdAt: '2026-02-12T10:15:00Z',
    updatedAt: '2026-02-12T11:00:00Z',
  },
  {
    id: 'ord-1003',
    orderNumber: 'MLM-2026-003',
    clientId: 'user-client-1',
    clientName: 'Josephine Mbemba (DEMO)',
    clientPhone: '+243810123456',
    items: [
      {
        id: 'item-3',
        productId: 'prod-5',
        productName: 'Smartphone Android 64GB Double SIM 5000mAh',
        productImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
        shopId: 'shop-4',
        shopName: 'Yoka High-Tech Mobile & Solaire',
        unitPrice: 175000,
        quantity: 1,
        totalPrice: 175000,
      },
    ],
    subtotal: 175000,
    deliveryFee: 0,
    totalAmount: 175000,
    status: 'confirmed',
    deliveryType: 'home_delivery',
    deliveryAddress: {
      city: 'Mbandaka',
      streetDetails: 'Av. Bolenge n° 14',
      recipientName: 'Josephine Mbemba',
      recipientPhone: '+243810123456',
    },
    paymentMethod: 'mpesa',
    paymentStatus: 'paid',
    paymentTransactionRef: 'MPESA-TEST-99211',
    isTestPayment: true,
    commissionTotal: 8750,
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-02-15T09:10:00Z',
  },
];

export const demoSubscriptions: MerchantSubscription[] = [
  {
    id: 'sub-1',
    userId: 'user-merchant-1',
    userName: 'Papa Jean-Luc Mboyo',
    shopName: 'Mboyo Vivres Frais & Terroir Mbandaka',
    shopId: 'shop-1',
    userPhone: '+243820234567',
    amountUsd: 4,
    amountFc: 11000,
    currency: 'USD',
    durationMonths: 3,
    status: 'PAID',
    paymentMethod: 'mpesa',
    transactionRef: 'SUB-MPESA-202601',
    startDate: '2026-01-01',
    endDate: '2026-04-01',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'sub-2',
    userId: 'user-merchant-2',
    userName: 'Maman Chantal Boketshu',
    shopName: 'Élégance Karawa - Wax & Confection',
    shopId: 'shop-2',
    userPhone: '+243899345678',
    amountUsd: 4,
    amountFc: 11000,
    currency: 'USD',
    durationMonths: 3,
    status: 'PAID',
    paymentMethod: 'airtel',
    transactionRef: 'SUB-AIRTEL-202602',
    startDate: '2026-01-05',
    endDate: '2026-04-05',
    createdAt: '2026-01-05T10:00:00Z',
  },
  {
    id: 'sub-3',
    userId: 'user-merchant-3',
    userName: 'Lokonda Bokele',
    shopName: 'Lokonda Chaussures & Terroir - Karawa',
    shopId: 'shop-3',
    userPhone: '+243990456789',
    amountUsd: 4,
    amountFc: 11000,
    currency: 'USD',
    durationMonths: 3,
    status: 'PAID',
    paymentMethod: 'mpesa',
    transactionRef: 'SUB-MPESA-202603',
    startDate: '2026-01-10',
    endDate: '2026-04-10',
    createdAt: '2026-01-10T11:00:00Z',
  },
];

export const demoReports: Report[] = [
  {
    id: 'rep-1',
    reporterName: 'Josephine Mbemba',
    reporterPhone: '+243810123456',
    reason: 'probleme_commande',
    targetType: 'commande',
    targetId: 'ord-1002',
    targetName: 'Commande MLM-2026-002',
    description: 'Le commerçant a convenu d’une livraison à domicile pour l’huile de palme mais a demandé un léger décalage d’horaire.',
    status: 'resolved',
    createdAt: '2026-02-12T12:00:00Z',
  },
];

export const demoReviews: Review[] = [
  {
    id: 'rev-1',
    shopId: 'shop-3',
    shopName: 'Lokonda Chaussures & Terroir - Karawa',
    clientId: 'user-client-1',
    clientName: 'Josephine Mbemba',
    rating: 5,
    comment: 'Superbes chaussures en cuir reçues directement à Karawa ! Le vendeur a lui-même confié le colis à un motard de confiance.',
    isApproved: true,
    createdAt: '2026-02-10T17:00:00Z',
  },
  {
    id: 'rev-2',
    shopId: 'shop-2',
    shopName: 'Élégance Karawa - Wax & Confection',
    clientId: 'user-client-1',
    clientName: 'Josephine Mbemba',
    rating: 5,
    comment: 'Très belle robe et chemise wax authentique. Maman Chantal a été très réactive sur WhatsApp.',
    isApproved: true,
    createdAt: '2026-02-11T12:00:00Z',
  },
];

export const demoCommissions: Commission[] = [
  {
    id: 'com-1',
    orderId: 'ord-1001',
    orderNumber: 'MLM-2026-001',
    shopId: 'shop-3',
    shopName: 'Lokonda Chaussures & Terroir - Karawa',
    orderAmount: 28000,
    ratePercent: 5,
    commissionAmount: 1400,
    merchantAmount: 26600,
    status: 'collected',
    createdAt: '2026-02-10T14:30:00Z',
  },
];

export const demoNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-client-1',
    title: 'Commande expédiée par le commerçant ! 📦',
    message: 'Votre commande MLM-2026-002 a été expédiée par Lokonda Chaussures Karawa.',
    type: 'order',
    isRead: false,
    linkUrl: '/orders/ord-1002',
    createdAt: '2026-02-12T11:05:00Z',
  },
];

export const defaultSettings: PlatformSettings = {
  commissionRate: 5, // 5%
  defaultCurrency: 'FC',
  platformName: 'MARCHE LUMUMBA RDC',
  supportPhone: '+243 833358006',
  supportWhatsapp: '+243 833358006',
  supportEmail: 'sitdoworldinformatique@gmail.com',
  subscriptionPriceUsd: 4,
  subscriptionPriceFc: 11000, // ~4 USD
  subscriptionPromoDurationMonths: 3,
  testPaymentMode: true,
  heroBannerImage: '/images/Supermarché moderne aux rayons colorés.jpg',
  marketLogoUrl: '/images/marche_lumumba_logo.jpg',
  mobileMoneyAccounts: {
    mpesaNumber: '+243 820 000 000',
    airtelNumber: '+243 990 000 000',
    orangeNumber: '+243 890 000 000',
    accountName: 'MARCHE LUMUMBA RDC SARL',
  },
};
